config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  resources :users
  resources :companies
  get '/users/:id/password_edit', to: 'users#editpass', as: 'password_edit'
  patch '/users/:id/password_edit', to: 'users#updatepass'
  get '/register/:id', to: 'users#register'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'admin_login' => 'sessions#new_admin'
  post 'admin_login' => 'sessions#create_admin'
  delete 'logout' => 'sessions#destroy'

  get 'admin' => 'admin#index'
  get 'stats' => 'admin#stats'

  get '/company_list' => 'getrequest#getcompanylist'
  get '/company_by_branch' => 'getrequest#company_by_branch'
  post '/apply/:id' => 'users#apply'
  post '/cancel/:id' => 'users#cancel_application'
  post '/confirm/:branch/:company/:list' => 'admin#confirm_application'
  post '/shortlist/:branch/:company/:list' => 'admin#confirm_application'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Training and Placement Cell</a>
    by <a href="http://www.nitc.ac.in">NIT Calicut</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "T & P", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_url %></li>
        <li><%= link_to "Help",   help_path %></li>
       <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Edit Password", password_edit_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
       <% else %>
            <li><%= link_to "Log in", login_path %></li>
       <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=  fulltitle(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app='tnpApp'>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type,message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>